public class SwarFarmMonster {

    private String id;
    private String url;
    private String com2us_id;
    private String family_id;
    private String name;
    private String image_filename;
    private String element;
     
    private Long base_stars;
    private Boolean obtainable;
    private Boolean can_awaken;
    private Boolean is_awakenend;
    private String awaken_bonus;
    private List<Long> skills;
    private Long skill_ups_to_max;
    private SwarFarmLeaderSkill leader_skill;
    private List<Long> homunculus_skills;
    private Long base_hp;
    private Long base_attack;
    private Long base_defense;
    private Long speed;
    private Long crit_rate;
    private Long crit_damage;
    private Long resistance;
    private Long accuracy;
    private Long raw_hp;
    private Long raw_attack;
    private Long raw_defense;
    private Long max_lvl_hp;
    private Long max_lvl_attack;
    private Long max_lvl_defense;
    private Long awakens_from;
    private Long awakens_to;
    private Long awaken_mats_fire_low;
    private Long awaken_mats_fire_mid;
    private Long awaken_mats_fire_high;
    private Long awaken_mats_water_low;
    private Long awaken_mats_water_mid;
    private Long awaken_mats_water_high;
    private Long awaken_mats_wind_low;
    private Long awaken_mats_wind_mid;
    private Long awaken_mats_wind_high;
    private Long awaken_mats_light_low;
    private Long awaken_mats_light_mid;
    private Long awaken_mats_light_high;
    private Long awaken_mats_dark_low;
    private Long awaken_mats_dark_mid;
    private Long awaken_mats_dark_high;
    private Long awaken_mats_magic_low;
    private Long awaken_mats_magic_mid;
    private Long awaken_mats_magic_high;
    private List<SwarFarmSource> source;
    private Boolean fusion_food;
    private SwarFarmResource resources;
    private Boolean homunculus;

}